### PR TITLE
Support mongo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by syuilo** [comment]
Status.find-by-id を使った方が良いかも

**Comment by ghost** [comment]
I see.
I use find-by-id.

**Comment by ghost** [comment]
I'm sorry. I fixed.

**Comment by syuilo** [comment]
| _ => Status.find-by-id target-status.repost-from-status-id の後に,が必要

**Comment by ghost** [comment]
I'm sorry.

**Pull request merged**
