### PR TITLE
Add node-gyp instructions to build the crypto module

### PR DESCRIPTION
**Pull request by Angristan**
Otherwise misskey can't run.

### CODE REVIEW

**Comment by syuilo** [comment]
Thank you👍

**Comment by angristan** [comment]
:+1:

**Comment by akihikodaki** [comment]
I remember NPM bundles node-gyp by default. Do you favor tell me your NPM installation?

**Comment by angristan** [comment]
I'm using Debian 9 and Node 9.

```bash
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs
```

What about you?

**Comment by akihikodaki** [comment]
Thank you for your information. I'm on Arch Linux, and its `npm` package is from `https://github.com/npm/npm/archive/v5.8.0.tar.gz`:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/npm
The notable difference is that it links `/usr/lib/node_modules/npm/node_modules/node-gyp/.bin/node-gyp` to `/usr/bin/node-gyp`.

I had look at `https://deb.nodesource.com/setup_9.x`. It certainly includes node-gyp at `/usr/lib/node_modules/npm/node_modules/node-gyp`.

So the symlink at `/usr/bin/node-gyp` is the only (notable) difference as far as I can tell. The symlink would be necessary to run:
> 2.  `node-gyp configure`
> 3. `node-gyp build`

That is an intended behavior, however, according to Node.js documentation:
> A version of the `node-gyp` utility is bundled and distributed with Node.js as part of `npm`. This version is not made directly available for developers to use and is intended only to support the ability to use the `npm install` command to compile and install Addons. Developers who wish to use node-gyp directly can install it using the command `npm install -g node-gyp`. See the `node-gyp` [installation instructions](https://github.com/nodejs/node-gyp#installation) for more information, including platform-specific requirements.

https://nodejs.org/api/addons.html

> If there is a `binding.gyp` file in the root of your package and you have not defined an `install` or `preinstall` script, npm will default the `install` command to compile using node-gyp.

https://docs.npmjs.com/files/package.json

You don't have to execute those commands, and `npm install` should be just enough, according to what it says. Something wen wrong, but I don't know exactly what is wrong  :confused: .

**Comment by angristan** [comment]
I tried again, and installing build-essential is all that's needed.

**Pull request merged**
