### PR TITLE
Update build docs

### PR DESCRIPTION
**Pull request by Angristan**
Fix #1474

### CODE REVIEW

**Comment by syuilo** [comment]
I am using Windows 10, and I needed `npm install -g node-gyp`.

**Comment by angristan** [comment]
Aaaaah

**Comment by angristan** [comment]
Better?

**Comment by syuilo** [comment]
Cool!

**Comment by syuilo** [comment]
Thank you @Angristan.

**Comment by angristan** [comment]
You're welcome!

**Comment by angristan** [comment]
You may want to update the Japanese docs too. I'm not fluent enough to do it!

**Pull request merged**
